services:
  tsp:
    image: ghcr.io/rtgnx/tsp:v0.0.1
    environment:
      TS_TAILNET: rtgnx.github
      TS_OAUTH_CLIENT_ID: file:/run/secrets/tsp_oauth_client_id
      TS_OAUTH_CLIENT_SECRET: file:/run/secrets/tsp_oauth_client_secret
      TS_TAGS: tag:docker # Associated tag with oauth credentials and autoapprovers
      SWARM_NETWORK: tsp-ingress
    secrets:
      - tsp_oauth_client_id
      - tsp_oauth_client_secret
    networks:
      - ts-ingress
    volumes:
      - tsp-state:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any

networks:
  ts-ingress:
    external: true
    name: tsp-ingress

volumes:
  tsp-state:

secrets:
  tsp_oauth_client_id:
    file: ./secrets/oauth_client_id.txt
  tsp_oauth_client_secret:
    file: ./secrets/oauth_client_secret.txt
